FROM php:8.4.19-fpm-alpine3.22

WORKDIR /app

COPY docker/php/conf.d/aurum.ini /usr/local/etc/php/conf.d/aurum.ini
COPY . /app

RUN adduser -D -u 1000 app \
    && chown -R app:app /app

USER app

CMD ["php-fpm"]
